import { chromium } from 'playwright-core';
const CHROME='/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const b=await chromium.launch({executablePath:CHROME});
const p=await b.newPage({viewport:{width:390,height:800}});
await p.goto('http://localhost:4189/cs2-Map-Callouts/',{waitUntil:'networkidle'});
await p.waitForTimeout(400);
await p.screenshot({path:'scratch/mobile_fixed.png'});
await p.click('.icon-toggle');
await p.waitForTimeout(350);
await p.screenshot({path:'scratch/mobile_fixed_open.png'});
await b.close();
console.log('done');
